#!/bin/bash
# 快速跳转工具 - 在 IDE 中无法跳转时使用

echo "=============================================="
echo "AgentDevProject 函数位置速查"
echo "=============================================="
echo ""
echo "📂 database.py"
echo "  init_db:        第 269 行"
echo "  drop_all:       第 282 行"
echo "  Session类:      第 160 行"
echo "  Message类:      第 195 行"
echo ""
echo "📂 init_db.py"
echo "  initialize_database:  第 119 行"
echo "  drop_all_tables:     第 102 行"
echo ""
echo "📂 session_service.py"
echo "  create_session:     第 31 行"
echo "  get_session:        第 72 行"
echo "  add_message:        第 178 行"
echo ""
echo "=============================================="
echo "使用方法："
echo "  1. 复制上面的行号"
echo "  2. 在 IDE 中按 Ctrl + G (Go to Line)"
echo "  3. 输入行号跳转"
echo "=============================================="
