#!/bin/bash
# 手动功能验证脚本

echo "=== 工具功能验证脚本 ==="
echo ""
echo "步骤1: 启动后端服务"
echo "cd backend && python -m uvicorn api.main:app --reload --port 8000"
echo ""
echo "步骤2: 获取认证Token"
echo "curl -X POST http://localhost:8000/api/auth/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"username\": \"admin\", \"password\": \"your_password\"}'"
echo ""
echo "步骤3: 测试DuckDuckGo搜索"
echo "curl -X POST http://localhost:8000/api/chat/sse \\"
echo "  -H \"Authorization: Bearer YOUR_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"message\": \"搜索今天的科技新闻\", \"agent_type\": \"react_agent\", \"session_id\": \"test-search-001\"}'"
echo ""
echo "步骤4: 测试LLM数学计算"
echo "curl -X POST http://localhost:8000/api/chat/sse \\"
echo "  -H \"Authorization: Bearer YOUR_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"message\": \"计算 123 * 456 + 789\", \"agent_type\": \"react_agent\", \"session_id\": \"test-math-001\"}'"
echo ""
echo "=== 预期结果 ==="
echo "- DuckDuckGo: 返回搜索结果（包含标题、链接、摘要），响应时间 < 5秒"
echo "- LLMMath: 返回答案 56877，响应时间 < 10秒"
